// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBot.Core.Contexts;

#nullable disable

namespace TelegramBot.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TelegramBot.Core.Entities.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("groupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ownerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TelegramBot.Core.Entities.GroupMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("groupid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("joinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<long>("telegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("groupid");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("TelegramBot.Core.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("registeredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("telegramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TelegramBot.Core.Entities.GroupMember", b =>
                {
                    b.HasOne("TelegramBot.Core.Entities.Group", "group")
                        .WithMany("Members")
                        .HasForeignKey("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("group");
                });

            modelBuilder.Entity("TelegramBot.Core.Entities.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
